# -*- coding: utf-8 -*-
"""BigDataAnalyticsHomework5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1at1tvozNl82aFbJlO47kRCnpqmggr2rN
"""

!pip install spacy
!pip install newsapi-python

!python -m spacy download en_core_web_lg

import spacy
import en_core_web_lg
from newsapi import NewsApiClient


nlp_eng = en_core_web_lg.load()
newsapi = NewsApiClient (api_key='d951e0e3fd844a1889fd7a557e9e51ea')

articles = newsapi.get_everything(q='coronavirus', language='en', from_param='2021-09-22', to='2021-10-22', sort_by='relevancy')

import pickle


filename = 'articlesCOVID.pckl'
pickle.dump(articles, open(filename, 'wb'))
filename = 'articlesCOVID.pckl'
loaded_model = pickle.load(open(filename, 'rb'))

filepath = 'content/sample_data/articlesCOVID.pckl'
pickle.dump(loaded_model, open(filepath, 'wb'))

import pandas as pd
dados = []
for i, article in enumerate(articles):
    for x in articles['articles']:
        title = x['title']
        description = x['description']
        date = x["publishedAt"]
        content = x['content']
        dados.append({'title':title, 'date':date, 'desc':description, 'content':content})
df = pd.DataFrame(dados)
df = df.dropna()
df.head()

if (token.text in nlp_eng.Defaults.stop_words or token.text in punctuation):
  continue
if (token.pos_ in pos_tag):
  result.append(token.text)
return result